version: '3'

services:
  yarn:
    image: node:alpine
    command: yarn install -g
    volumes:
      - .:/code
    working_dir: /code
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - yarn
