version: '3'

services:
  yarn:
    image: django-restaurant_web
    volumes:
      - .:/code
    command: yarn install -g
  db:
    image: postgres:11.2
  migrate:
    image: django-restaurant_web
    command: python3 manage.py migrate
    depends_on:
      - db
  gulp:
    image: django-restaurant_web
    volumes:
      - .:/code
    command: yarn run gulp
    depends_on:
      - yarn
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migrate
      - yarn
