# Generated by Django 2.0.7 on 2018-07-29 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=2018, max_length=4, verbose_name='Year')),
                ('period', models.CharField(choices=[('1', 'I'), ('2', 'II')], max_length=1, verbose_name='Period')),
                ('start_date', models.DateField(default=datetime.datetime(2018, 7, 29, 4, 19, 52, 967546, tzinfo=utc), verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 7, 29, 4, 19, 52, 967598, tzinfo=utc), verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('year', 'period')},
        ),
    ]
