# Generated by Django 2.1 on 2018-08-10 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_studentuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('call', '0002_auto_20180730_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('consecutive', models.AutoField(primary_key=True, serialize=False, verbose_name='Consecutive')),
                ('status', models.CharField(choices=[('Processing', 'processing'), ('Approved', 'approved'), ('Canceled', 'canceled'), ('Verified', 'verified'), ('Insufficient', 'insufficient')], max_length=12, verbose_name='Status')),
                ('received_at', models.DateField(default=django.utils.timezone.now, verbose_name='Received at')),
                ('score', models.SmallIntegerField(null=True, verbose_name='Score')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call', to='call.Call', verbose_name='Call')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='user.StudentUser', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(max_length=50, upload_to='application/', verbose_name='Attachment')),
                ('condition_value', models.CharField(max_length=10, verbose_name='Condition Value')),
                ('condition_score', models.PositiveSmallIntegerField(null=True, verbose_name='Condition Score')),
                ('condition_status', models.CharField(max_length=10, null=True, verbose_name='Condition Status')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='call.Application', verbose_name='Application')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='call.Conditon', verbose_name='Condition')),
            ],
        ),
    ]
